version: 2
updates:
- package-ecosystem: "cargo"
  directory: "/ledger"
  schedule:
    interval: "daily"
- package-ecosystem: "cargo"
  directory: "/tmpfs"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
