name: build

on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        config:
        - host: macos-latest
          system: x86_64-darwin
          target: aarch64-apple-darwin

        - host: macos-latest
          system: x86_64-darwin
          target: x86_64-apple-darwin

        - host: ubuntu-latest
          system: x86_64-linux
          target: aarch64-unknown-linux-musl

        - host: ubuntu-latest
          system: x86_64-linux
          target: x86_64-unknown-linux-musl

    runs-on: ${{ matrix.config.host }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ github.token }}
    - uses: cachix/cachix-action@v12
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: rustup show
    - run: cargo update
    - run: git add -f Cargo.lock
    - run: nix build -L --show-trace '.#checks.${{ matrix.config.system }}.vfs-${{ matrix.config.target }}'
